import { Question, Category } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Prompt Engineering',
    description: '提示词工程相关题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'AI Agent',
    description: 'AI Agent架构设计与核心概念题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'RAG',
    description: '检索增强生成相关题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'LLM基础',
    description: '大语言模型基础与工程实践题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'MCP协议',
    description: 'Model Context Protocol相关题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'AI系统设计',
    description: 'AI应用系统设计与架构题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: '向量数据库',
    description: '向量数据库与索引算法题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Agent Memory',
    description: 'Agent记忆系统相关题目',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const mockQuestions: Question[] = [
  // ============ LLM基础 ============
  {
    id: '1',
    user_id: 'user-1',
    category_id: '4',
    title: 'Token是什么？为什么中文、英文、代码消耗的Token不一样？',
    content: '请解释大模型中Token的概念，并说明为什么不同语言和代码消耗的Token数量不同。',
    options: [
      'A. Token是模型处理文本的基本单位，不同语言的分词方式不同',
      'B. Token就是字符，每个字符算一个Token',
      'C. Token是模型的参数单位',
      'D. Token只影响显示，不影响计算',
    ],
    answer: 'A',
    explanation: 'Token是大模型处理文本的基本单位，但不是简单的字符。不同语言使用不同的分词器，中文通常需要更多Token来表达相同含义，代码的特殊符号也会产生较多Token。Token直接影响上下文容量、推理成本和响应延迟。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    category: mockCategories[3],
  },
  {
    id: '2',
    user_id: 'user-1',
    category_id: '4',
    title: '上下文窗口越大，效果一定越好吗？',
    content: '大模型的上下文窗口（Context Window）越大是否意味着效果越好？请分析其利弊。',
    options: [
      'A. 不一定，大窗口会增加成本、延迟和噪声风险',
      'B. 是的，窗口越大效果一定越好',
      'C. 窗口大小对效果没有影响',
      'D. 只影响存储，不影响效果',
    ],
    answer: 'A',
    explanation: '上下文窗口越大，单次能处理的信息越多，但同时会增加推理成本、响应延迟，并可能出现"Lost in the Middle"问题（模型忽略中间内容）。生产环境中需要根据任务需求合理设置窗口大小，而非盲目追求最大窗口。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
    category: mockCategories[3],
  },
  {
    id: '3',
    user_id: 'user-1',
    category_id: '4',
    title: 'Temperature参数如何影响模型输出？',
    content: 'Temperature参数在大模型中控制什么？生产环境中应该如何设置？',
    options: [
      'A. 控制采样分布的随机性，生产环境通常设置较低值以保证稳定性',
      'B. 控制模型的训练速度',
      'C. 控制输出文本的长度',
      'D. 控制模型的参数量',
    ],
    answer: 'A',
    explanation: 'Temperature控制模型输出的随机性：值越高输出越随机多样，值越低输出越确定稳定。生产环境通常设置0-0.3以保证输出的可复现性和稳定性，创意类任务可适当提高。Temperature=0时输出仍可能有微小差异，因为硬件和并行处理会引入微小不确定性。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
    category: mockCategories[3],
  },
  {
    id: '4',
    user_id: 'user-2',
    category_id: '4',
    title: '大模型为什么会产生幻觉？',
    content: '大模型产生幻觉（Hallucination）的原因是什么？有哪些常见的缓解方案？',
    options: [
      'A. 训练数据偏差、概率采样、缺乏事实验证，可通过RAG、工具调用、输出校验缓解',
      'B. 模型故意说谎',
      'C. 只是计算错误',
      'D. 幻觉无法缓解',
    ],
    answer: 'A',
    explanation: '幻觉产生的原因包括：训练数据中的错误信息、模型基于概率生成可能不准确的内容、缺乏实时信息获取能力。缓解方案包括：RAG提供外部证据、Function Calling获取实时数据、输出校验、引用来源、评测闭环等。单靠某个参数无法完全消除幻觉。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    category: mockCategories[3],
  },
  {
    id: '5',
    user_id: 'user-2',
    category_id: '4',
    title: '什么是Lost in the Middle问题？',
    content: '请解释大模型中的Lost in the Middle问题，以及如何在长上下文场景下缓解它。',
    options: [
      'A. 模型倾向于关注输入的开头和结尾，忽略中间内容，可通过重排、摘要缓解',
      'B. 模型丢失了训练数据',
      'C. 模型内存不足',
      'D. 网络传输丢失数据',
    ],
    answer: 'A',
    explanation: 'Lost in the Middle是指大模型在处理长文本时，倾向于关注开头和结尾的信息，而忽略中间部分的内容。缓解方法包括：将重要信息放在输入的开头或结尾、使用Rerank重排检索结果、对长文本进行分段摘要、使用滑动窗口等策略。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    category: mockCategories[3],
  },
  // ============ AI Agent ============
  {
    id: '6',
    user_id: 'user-2',
    category_id: '2',
    title: 'AI Agent是什么？和普通Chatbot有什么区别？',
    content: '请解释AI Agent的核心概念，以及它与普通聊天机器人的本质区别。',
    options: [
      'A. Agent能多步骤执行任务并调用外部工具，Chatbot主要用于问答',
      'B. Agent就是更高级的Chatbot',
      'C. 两者没有区别',
      'D. Chatbot能执行任务，Agent不能',
    ],
    answer: 'A',
    explanation: 'AI Agent是围绕大模型构建的任务执行系统，具有规划、记忆、工具调用和自主决策能力，能完成多步骤复杂任务。普通Chatbot主要基于单轮或简单多轮对话进行问答，缺乏自主规划和工具调用能力。Agent的核心是"行动"而非仅仅是"回答"。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
    category: mockCategories[1],
  },
  {
    id: '7',
    user_id: 'user-2',
    category_id: '2',
    title: 'Agent Loop的完整流程是什么？',
    content: '请描述Agent Loop（智能体循环）的完整工作流程，包括各个阶段的作用。',
    options: [
      'A. 观察→推理→行动→观察结果，循环执行直到任务完成',
      'B. 只执行一次就结束',
      'C. 直接输出答案',
      'D. 随机选择行动',
    ],
    answer: 'A',
    explanation: 'Agent Loop的标准流程是：1) 观察(Observe) - 获取当前状态和环境信息；2) 推理(Think) - 分析情况并制定计划；3) 行动(Act) - 执行工具调用或生成输出；4) 观察结果 - 检查行动效果。这个循环持续进行直到任务完成或达到停止条件。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
    category: mockCategories[1],
  },
  {
    id: '8',
    user_id: 'user-3',
    category_id: '2',
    title: 'Agent和Workflow的核心区别是什么？',
    content: '在什么场景下应该使用纯Agent，什么场景下应该使用Workflow？',
    options: [
      'A. Agent适合路径不确定的开放任务，Workflow适合流程固定的可控场景',
      'B. 总是应该用Agent',
      'C. 总是应该用Workflow',
      'D. 两者完全相同',
    ],
    answer: 'A',
    explanation: 'Agent通过动态决策应对不确定的任务路径，适合探索性、多变的任务；Workflow预定义了固定的执行路径，适合流程清晰、需要可控性和可预测性的场景。生产环境中，To B场景通常优先选择Workflow或Agentic Workflow，将关键路径控制住，只在必要节点让模型做判断。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
    category: mockCategories[1],
  },
  {
    id: '9',
    user_id: 'user-3',
    category_id: '2',
    title: 'ReAct、Plan-and-Execute、Reflection分别适合什么场景？',
    content: '请比较ReAct、Plan-and-Execute和Reflection这三种Agent架构模式的适用场景。',
    options: [
      'A. ReAct适合简单任务，Plan-and-Execute适合复杂规划任务，Reflection适合需要迭代优化的任务',
      'B. 三者完全相同',
      'C. 只有ReAct可用',
      'D. 这些架构已过时',
    ],
    answer: 'A',
    explanation: 'ReAct（推理+行动）适合简单的推理和工具调用任务；Plan-and-Execute将规划和执行分离，适合需要预先规划的复杂任务；Reflection让Agent反思自己的输出并迭代改进，适合需要高质量输出的场景。选择时要考虑任务复杂度、调试成本和容错要求。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2024-01-09T00:00:00Z',
    category: mockCategories[1],
  },
  // ============ Agent Memory ============
  {
    id: '10',
    user_id: 'user-1',
    category_id: '8',
    title: 'Agent的短期记忆和长期记忆有什么区别？',
    content: '请解释Agent记忆系统中短期记忆和长期记忆的区别及其各自的作用。',
    options: [
      'A. 短期记忆是当前任务的状态信息，长期记忆是跨会话的知识和经验',
      'B. 两者没有区别',
      'C. 短期记忆容量更大',
      'D. 长期记忆只能存储文本',
    ],
    answer: 'A',
    explanation: '短期记忆（Short-term Memory）类似工作记忆，负责保存当前任务执行过程中的状态、中间结果和上下文，任务结束后通常丢弃。长期记忆（Long-term Memory）负责跨会话持久化用户偏好、历史决策、经验和知识，需要考虑存储、检索、更新和隐私治理。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    category: mockCategories[7],
  },
  {
    id: '11',
    user_id: 'user-1',
    category_id: '8',
    title: '向量记忆和Markdown记忆分别适合什么场景？',
    content: 'Agent记忆系统中，向量记忆和Markdown记忆各有什么特点和适用场景？',
    options: [
      'A. 向量记忆适合语义检索，Markdown记忆适合规则、偏好等可读可审查的信息',
      'B. 两者完全相同',
      'C. 只有向量记忆可用',
      'D. Markdown记忆更适合搜索',
    ],
    answer: 'A',
    explanation: '向量记忆将信息编码为向量，适合基于语义相似度的模糊检索，如"找到类似的问题"。Markdown记忆以结构化文本存储，适合存储规则、用户偏好、项目约定等需要人类可读、可审查、可版本控制的信息。两者可以组合使用，各取所长。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-11T00:00:00Z',
    updated_at: '2024-01-11T00:00:00Z',
    category: mockCategories[7],
  },
  {
    id: '12',
    user_id: 'user-2',
    category_id: '8',
    title: '如何避免长期记忆污染上下文？',
    content: 'Agent在使用长期记忆时，如何避免记忆信息污染当前上下文？',
    options: [
      'A. 通过相关性检索、过滤、压缩和作用域控制',
      'B. 把所有记忆都加入上下文',
      'C. 不使用长期记忆',
      'D. 只使用最新记忆',
    ],
    answer: 'A',
    explanation: '避免记忆污染的方法包括：1) 基于任务相关性检索，而非全量注入；2) 设置记忆的作用域和有效期；3) 对记忆内容进行过滤和去重；4) 控制注入记忆的数量和Token预算；5) 使用优先级和权重机制；6) 定期清理过期或低质量记忆。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
    category: mockCategories[7],
  },
  // ============ Context Engineering ============
  {
    id: '13',
    user_id: 'user-1',
    category_id: '1',
    title: 'Prompt Engineering和Context Engineering有什么区别？',
    content: '请解释Prompt Engineering和Context Engineering的区别，以及它们各自关注的重点。',
    options: [
      'A. Prompt关注指令怎么写清楚，Context关注什么信息在什么时机进入模型窗口',
      'B. 两者完全相同',
      'C. Context Engineering比Prompt Engineering更简单',
      'D. Prompt Engineering已经过时',
    ],
    answer: 'A',
    explanation: 'Prompt Engineering关注如何设计清晰、有效的指令，包括角色设定、任务描述、格式要求等。Context Engineering更关注整个信息流：什么信息应该进入上下文、什么时候进入、如何组织、如何压缩、如何处理溢出。在Agent场景下，Context Engineering往往比Prompt Engineering更重要。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-13T00:00:00Z',
    updated_at: '2024-01-13T00:00:00Z',
    category: mockCategories[0],
  },
  {
    id: '14',
    user_id: 'user-2',
    category_id: '1',
    title: '什么是Prompt注入攻击？如何防护？',
    content: '请解释Prompt注入攻击的原理，以及常见的防护方式。',
    options: [
      'A. 攻击者通过输入操纵模型行为，防护需结合权限隔离、输入过滤、输出校验',
      'B. 只需要提醒模型不要听从恶意指令',
      'C. Prompt注入无法防护',
      'D. 只有付费模型才能防护',
    ],
    answer: 'A',
    explanation: 'Prompt注入是攻击者通过精心构造的输入，试图绕过系统指令让模型执行非预期操作。防护措施包括：1) 输入过滤和清洗；2) 系统指令与用户输入分离；3) 权限隔离和工具白名单；4) 输出校验和审计；5) 使用专门的防护模型或分类器。单纯靠Prompt提醒模型是不够的。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-14T00:00:00Z',
    updated_at: '2024-01-14T00:00:00Z',
    category: mockCategories[0],
  },
  // ============ MCP协议 ============
  {
    id: '15',
    user_id: 'user-1',
    category_id: '5',
    title: 'MCP解决什么问题？为什么常被类比成AI领域的USB-C？',
    content: '请解释MCP（Model Context Protocol）的核心价值，以及为什么它被类比为USB-C。',
    options: [
      'A. MCP标准化了工具接入方式，让AI应用能即插即用地连接各种工具和数据源',
      'B. MCP只是一种新的编程语言',
      'C. MCP只用于文本处理',
      'D. MCP是硬件接口标准',
    ],
    answer: 'A',
    explanation: 'MCP解决的核心问题是工具接入的标准化。就像USB-C统一了设备接口一样，MCP为AI应用提供了统一的工具发现、描述、调用和返回结果的协议。这使得一次开发的工具可以被多个AI应用复用，避免了每个应用都需要单独适配的重复工作。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    category: mockCategories[4],
  },
  {
    id: '16',
    user_id: 'user-2',
    category_id: '5',
    title: 'MCP和Function Calling有什么区别？',
    content: '请解释MCP和Function Calling的区别，以及它们各自解决的问题。',
    options: [
      'A. Function Calling是模型表达调用意图，MCP是工具标准化接入宿主',
      'B. 两者完全相同',
      'C. Function Calling更先进',
      'D. MCP只能用于GPT模型',
    ],
    answer: 'A',
    explanation: 'Function Calling解决的是"模型如何表达要调用哪个工具、传什么参数"，是模型输出结构化调用意图的能力。MCP解决的是"工具如何被标准化发现、描述、调用和返回结果"，是工具接入的协议标准。两者不在同一层，可以组合使用：模型通过Function Calling表达意图，通过MCP与实际工具交互。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-16T00:00:00Z',
    updated_at: '2024-01-16T00:00:00Z',
    category: mockCategories[4],
  },
  {
    id: '17',
    user_id: 'user-3',
    category_id: '5',
    title: '生产级MCP Server需要做哪些安全治理？',
    content: '将MCP Server部署到生产环境时，需要考虑哪些安全治理措施？',
    options: [
      'A. 权限控制、参数校验、审计日志、超时控制、速率限制、错误处理',
      'B. 只需要基本的API密钥',
      'C. 不需要特殊安全措施',
      'D. 只需要防火墙',
    ],
    answer: 'A',
    explanation: '生产级MCP Server需要多层安全治理：1) 身份认证和权限控制；2) 输入参数校验防止注入；3) 审计日志记录所有调用；4) 超时控制防止长时间占用资源；5) 速率限制防止滥用；6) 熔断和降级策略；7) 敏感数据脱敏；8) 工具调用的二次确认机制。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-17T00:00:00Z',
    updated_at: '2024-01-17T00:00:00Z',
    category: mockCategories[4],
  },
  // ============ RAG ============
  {
    id: '18',
    user_id: 'user-1',
    category_id: '3',
    title: 'RAG和微调怎么选？',
    content: '在什么场景下应该选择RAG，什么场景下应该选择微调（Fine-tuning）？',
    options: [
      'A. 知识频繁变化、需要引用来源时用RAG，要固定风格或能力倾向时用微调',
      'B. 总是应该用RAG',
      'C. 总是应该用微调',
      'D. 两者完全相同',
    ],
    answer: 'A',
    explanation: 'RAG适合：知识频繁更新、需要引用来源和溯源、有大量私有文档、需要控制成本的场景。微调适合：需要固定输出风格或格式、需要增强特定领域能力、对响应延迟要求高的场景。两者也可以结合使用：微调增强模型能力，RAG提供外部知识。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-18T00:00:00Z',
    updated_at: '2024-01-18T00:00:00Z',
    category: mockCategories[2],
  },
  {
    id: '19',
    user_id: 'user-2',
    category_id: '3',
    title: 'RAG召回率低应该怎么排查？',
    content: '当RAG系统出现召回率低的问题时，应该按照什么路径进行排查？',
    options: [
      'A. 按文档处理→召回阶段→排序阶段→上下文阶段→生成阶段逐步排查',
      'B. 直接换更大的模型',
      'C. 只调整TopK参数',
      'D. 增加更多文档',
    ],
    answer: 'A',
    explanation: 'RAG问题排查应该分阶段进行：1) 检查文档解析和Chunk质量；2) 确认正确文档是否进入候选池；3) 检查排序是否合理，是否需要Rerank；4) 检查上下文是否被截断或污染；5) 检查模型是否正确使用证据。不要一上来就改Prompt，先定位问题发生在哪个阶段。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-19T00:00:00Z',
    updated_at: '2024-01-19T00:00:00Z',
    category: mockCategories[2],
  },
  {
    id: '20',
    user_id: 'user-3',
    category_id: '3',
    title: 'Chunk切分为什么不能只按固定长度切？',
    content: 'RAG系统中文档Chunk切分时，为什么不能简单地按固定长度切分？',
    options: [
      'A. 固定切分会破坏语义完整性，应按标题、段落、语义边界切分',
      'B. 固定切分是最佳实践',
      'C. Chunk大小不影响效果',
      'D. 只能按句子切分',
    ],
    answer: 'A',
    explanation: '固定长度切分会带来问题：1) 可能切断完整的语义单元；2) 表格、代码块可能被破坏；3) 无法保留标题层级和上下文关系。更好的方式是：按标题层级和段落边界切分，对表格、代码、FAQ做特殊处理，保留父级标题作为元数据，通过评测验证Chunk策略的效果。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
    category: mockCategories[2],
  },
  {
    id: '21',
    user_id: 'user-1',
    category_id: '3',
    title: 'Hybrid Search是什么？BM25和向量检索怎么融合？',
    content: '请解释Hybrid Search的概念，以及如何融合BM25关键词检索和向量语义检索。',
    options: [
      'A. 结合关键词检索和向量检索，通过分数融合或排序融合提升召回质量',
      'B. 只使用向量检索',
      'C. 只使用关键词检索',
      'D. 两种检索不能融合',
    ],
    answer: 'A',
    explanation: 'Hybrid Search结合了BM25（基于词频的关键词检索）和向量检索（基于语义相似度）的优势。融合方式包括：1) 分数融合 - 将两种检索的分数归一化后加权求和；2) 排序融合 - 分别取TopK后合并重排。Hybrid Search特别适合专业术语、编号、实体名与语义表达混杂的场景。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-21T00:00:00Z',
    updated_at: '2024-01-21T00:00:00Z',
    category: mockCategories[2],
  },
  // ============ 向量数据库 ============
  {
    id: '22',
    user_id: 'user-2',
    category_id: '7',
    title: '什么是Embedding？为什么需要把文本转成向量？',
    content: '请解释Embedding的概念，以及为什么在RAG等场景中需要将文本转换为向量表示。',
    options: [
      'A. Embedding将文本映射到语义向量空间，相似文本距离更近，便于语义检索',
      'B. 向量化只是为了压缩文本',
      'C. 向量化会丢失语义信息',
      'D. Embedding只用于图像处理',
    ],
    answer: 'A',
    explanation: 'Embedding是将文本、图像等数据映射到高维向量空间的过程。在向量空间中，语义相似的内容距离更近，这使得我们可以通过计算向量距离来进行语义检索。相比传统关键词匹配，Embedding能理解同义词、近义表达和上下文含义，大幅提升检索的召回率。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-22T00:00:00Z',
    updated_at: '2024-01-22T00:00:00Z',
    category: mockCategories[6],
  },
  {
    id: '23',
    user_id: 'user-3',
    category_id: '7',
    title: 'HNSW和IVFFLAT索引有什么区别？',
    content: '请比较HNSW和IVFFLAT两种向量索引算法的优缺点和适用场景。',
    options: [
      'A. HNSW查询快但内存成本高，IVFFLAT更节省资源但依赖参数调优',
      'B. 两者完全相同',
      'C. HNSW只适合小数据集',
      'D. IVFFLAT查询更快',
    ],
    answer: 'A',
    explanation: 'HNSW（Hierarchical Navigable Small World）通过构建多层图结构实现快速近似最近邻搜索，查询速度快、召回率高，但内存占用较大。IVFFLAT（Inverted File Index）通过聚类将向量分组，内存效率更高，但查询性能依赖聚类质量和参数设置。HNSW适合对查询延迟要求高的场景，IVFFLAT适合资源受限的大规模场景。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-23T00:00:00Z',
    updated_at: '2024-01-23T00:00:00Z',
    category: mockCategories[6],
  },
  {
    id: '24',
    user_id: 'user-1',
    category_id: '7',
    title: '向量数据从100万增长到1亿，架构上需要做什么调整？',
    content: '当向量数据量从100万增长到1亿时，需要对架构进行哪些调整？',
    options: [
      'A. 分布式部署、索引分片、缓存策略、查询优化、资源扩容',
      'B. 只需要增加内存',
      'C. 不需要任何调整',
      'D. 只需要换更大的服务器',
    ],
    answer: 'A',
    explanation: '大规模向量数据需要：1) 分布式向量数据库，支持水平扩展；2) 索引分片和负载均衡；3) 热点数据缓存；4) 查询优化，如近似搜索精度调整；5) 批量导入和增量更新策略；6) 监控和运维体系建设。选择支持分布式架构的专业向量数据库（如Milvus、Weaviate）通常更合适。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-24T00:00:00Z',
    updated_at: '2024-01-24T00:00:00Z',
    category: mockCategories[6],
  },
  // ============ AI系统设计 ============
  {
    id: '25',
    user_id: 'user-2',
    category_id: '6',
    title: '为什么生产级AI应用需要模型网关？',
    content: '请解释大模型网关（LLM Gateway）的作用和核心能力。',
    options: [
      'A. 统一管理多模型路由、fallback、限流、成本控制和观测审计',
      'B. 只是转发请求',
      'C. 只用于负载均衡',
      'D. 网关会降低性能',
    ],
    answer: 'A',
    explanation: '大模型网关的核心价值：1) 多模型路由 - 根据任务选择最合适的模型；2) Fallback - 主模型失败时自动切换备用模型；3) 限流和熔断 - 保护系统稳定性；4) Token预算和成本归因 - 控制开支；5) 统一观测和审计 - 记录所有调用；6) 缓存策略 - 降低成本和延迟。网关让业务代码与具体模型供应商解耦。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-25T00:00:00Z',
    updated_at: '2024-01-25T00:00:00Z',
    category: mockCategories[5],
  },
  {
    id: '26',
    user_id: 'user-3',
    category_id: '6',
    title: '大模型调用为什么必须做幂等？',
    content: '为什么在生产环境中，大模型API调用必须设计幂等性？',
    options: [
      'A. 防止重试导致重复扣费、重复执行工具、数据不一致',
      'B. 幂等只影响性能',
      'C. 幂等不重要',
      'D. 只有支付接口需要幂等',
    ],
    answer: 'A',
    explanation: '大模型调用可能因网络超时、服务端错误等原因需要重试，如果没有幂等设计：1) 可能导致重复扣费；2) 工具调用可能被执行多次（如重复发邮件）；3) 数据可能被重复写入。幂等设计确保相同请求多次执行产生相同结果，通常通过请求ID去重实现。',
    difficulty: 'medium',
    is_public: true,
    created_at: '2024-01-26T00:00:00Z',
    updated_at: '2024-01-26T00:00:00Z',
    category: mockCategories[5],
  },
  {
    id: '27',
    user_id: 'user-1',
    category_id: '6',
    title: 'AI应用的评测为什么必须形成闭环？',
    content: '为什么AI应用需要建立从Golden Set到线上灰度的完整评测闭环？',
    options: [
      'A. 只有形成闭环才能持续发现问题、验证改进、防止退化',
      'B. 评测只在上线前做一次就够了',
      'C. 线上效果不需要验证',
      'D. 评测会降低开发效率',
    ],
    answer: 'A',
    explanation: 'AI应用的评测闭环包括：1) Golden Set离线回归 - 确保基础质量；2) Trace回放 - 覆盖真实线上路径；3) 线上灰度 - 验证真实用户分布；4) 失败样本回流 - 持续改进评测集。没有闭环，优化就靠感觉，新功能可能破坏旧功能，问题难以复现和定位。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-27T00:00:00Z',
    updated_at: '2024-01-27T00:00:00Z',
    category: mockCategories[5],
  },
  // ============ 原有题目 ============
  {
    id: '28',
    user_id: 'user-1',
    category_id: '1',
    title: '什么是零样本学习？',
    content: '请解释什么是零样本学习（Zero-shot Learning），并举例说明其在AI Agent中的应用场景。',
    options: [
      'A. 模型从未见过的任务也能完成',
      'B. 只使用零个样本进行训练',
      'C. 模型输出为零',
      'D. 无监督学习的一种',
    ],
    answer: 'A',
    explanation: '零样本学习是指模型在从未见过某个任务或类别的样本情况下，仍然能够完成该任务。在AI Agent中，这意味着Agent可以处理训练数据中不存在的任务类型，通过理解自然语言指令来执行新任务。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-28T00:00:00Z',
    updated_at: '2024-01-28T00:00:00Z',
    category: mockCategories[0],
  },
  {
    id: '29',
    user_id: 'user-2',
    category_id: '1',
    title: 'Few-shot学习与Zero-shot学习的区别是什么？',
    content: '请比较Few-shot学习和Zero-shot学习的区别，并说明各自的适用场景。',
    options: [
      'A. Few-shot需要少量示例，Zero-shot不需要',
      'B. 两者完全相同',
      'C. Few-shot需要大量示例',
      'D. Zero-shot需要更多计算资源',
    ],
    answer: 'A',
    explanation: 'Zero-shot学习是指模型在没有任何示例的情况下完成任务，依赖于预训练时学到的泛化能力。Few-shot学习则提供少量（通常是1-10个）示例让模型参考。Zero-shot适用于任务描述清晰的场景，Few-shot适用于需要更具体指导的复杂任务。',
    difficulty: 'easy',
    is_public: true,
    created_at: '2024-01-29T00:00:00Z',
    updated_at: '2024-01-29T00:00:00Z',
    category: mockCategories[0],
  },
  {
    id: '30',
    user_id: 'user-3',
    category_id: '2',
    title: 'Multi-Agent协作的主要问题是什么？',
    content: '多Agent系统在生产环境中面临哪些主要挑战？为什么不能盲目上多Agent？',
    options: [
      'A. 通信成本高、调试困难、一致性难保证、状态同步复杂',
      'B. 多Agent总是比单Agent好',
      'C. 多Agent没有缺点',
      'D. 只需要增加Agent数量',
    ],
    answer: 'A',
    explanation: 'Multi-Agent的主要挑战：1) 通信开销大，Agent间消息传递消耗Token和时间；2) 调试困难，难以追踪问题出在哪个Agent；3) 一致性难保证，不同Agent可能产生矛盾输出；4) 状态同步复杂，需要设计共享记忆机制。生产环境中应先评估是否真正需要多Agent，避免过度设计。',
    difficulty: 'hard',
    is_public: true,
    created_at: '2024-01-30T00:00:00Z',
    updated_at: '2024-01-30T00:00:00Z',
    category: mockCategories[1],
  },
];
